# Site settings
title: SmartYi
SEOTitle: MK的博客 | SmartYi Blog
header-img: img/home-bg.jpg
email: limkuan24@gmail.com
description: "Try everything"
keyword: "Android"
url: "http://smartyi.tk"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     limkuan
zhihu_username:     li-ming-kuan
github_username:    widelee
#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js", "package.json", "README.md", "README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Netease setttings
netease_comment: true

# Duoshuo settings
# duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: nothing <4cc1f2d8f3067386cc5cdb626a202900>
# Google Analytics
ga_track_id: 'UA-100591812-1'            # Format: UA-xxxxxx-xx
ga_domain: smartyi.tk



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Try Everything"
sidebar-avatar: /img/avatar-limk.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
         title: "Hux Blog",
         href: "http://huangxuan.me"
    },{
         title: "HelloKenLee Blog",
         href: "https://hellokenlee.github.io/"
    }
    # ,{
    #     title: "Bar",
    #     href: "#"
    # },{
    #     title: "Example Friends",
    #     href: "#"
    # },{
    #     title: "It helps SEO",
    #     href: "#"
    # }
]
